Repository chatwoot/charts, pull requests merged in 2022-02, with the labels that each got.

#53 Add ingressClass support
  charts/chatwoot/Chart.yaml
  charts/chatwoot/templates/ingress.yaml
  charts/chatwoot/values.yaml
Labels: enhancement, post-planning

#45 Apply tolerations and nodeSelector to pods in the chart
  .gitignore
  charts/chatwoot/Chart.yaml
  charts/chatwoot/templates/migrations-job.yaml
  charts/chatwoot/templates/tests/test-connection.yaml
  charts/chatwoot/templates/web-deployment.yaml
  charts/chatwoot/templates/worker-deployment.yaml
Labels: enhancement

#54 feat: update charts to chatwoot v2.2.0
  charts/chatwoot/Chart.yaml
  charts/chatwoot/README.md
  charts/chatwoot/values.yaml
Labels: post-planning
